name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: lowlighter/metrics@latest
        with:
          filename: public/metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: none
          config_timezone: Asia/Shanghai
          base: header, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_sections: base
          plugin_lines_delay: 30
          plugin_languages: yes
          plugin_languages_details: percentage, bytes-size
          plugin_followup: yes
          plugin_followup_sections: user
      - name: Commit metrics
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add public/metrics.svg
          git commit -m "Update metrics" || exit 0
          git push
